"use client";
import Navbar from "@/components/shared/Navbar";
import "./globals.css";
import { Roboto } from "next/font/google";
import { Provider } from "react-redux";
import store from "@/store/index";
import { Analytics } from "@vercel/analytics/react";
import Script from "next/script";
import Footer from "@/components/shared/Footer";
import CookieBanner from "@/components/shared/CookieBanner";

const roboto = Roboto({ subsets: ["latin"], weight: "300" });

// export const metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// 	width: "device-width",
// 	initialScale: 1,
// };

export default ({ children }) => {
	return (
		<html lang="en">
			{/* <Script
				strategy="lazyOnload"
				src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS}`}
			/>

			<Script strategy="lazyOnload">
				{`
				window.dataLayer = window.dataLayer || [];
				function gtag(){dataLayer.push(arguments);}
				gtag('js', new Date());
				gtag('config', '${process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS}', {
				page_path: window.location.pathname,
				});
		`}
			</Script> */}

			<body className={`${roboto.className} bg-white text-[#0f2740]`}>
				<Provider store={store}>
					<Navbar />
					{children}

					<Footer />
					<CookieBanner />
					<Analytics />
				</Provider>
			</body>
		</html>
	);
};
